name: artifact

on: [push]
env:
  ARTIFACT_NAME: app
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses : actions/checkout@v3
      - name : upload artifact
        uses : actions/upload-artifact@v3  
       
