name: artifact

on: [push]
env:
  ARTIFACT_NAME: app
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses : actions/checkout@v3
      - name : upload artifact
        uses : actions/upload-artifact@v3
        with :
          name : ${{ env.ARTIFACT_NAME }}
          path : .    
  use:
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses : actions/checkout@v3
      - name : Download a Build Artifact
        uses : actions/download-artifact@v2.1.1
        with :
          name : ${{ env.ARTIFACT_NAME }}
