name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python environement
      uses: actions/setup-python@v3
    - name: Install requirement 
      run: pip install --quiet --requirement requirements.txt
    - name: Lint code
      run:  pylint --disable=C0301  *.py
    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast
